### ISSUE TITLE
`IllegalArgumentException` when calling `gsub`

### ISSUE THREAD

**Issue by SquidDev** [SquidDev/Cobalt#78]
`string.gsub("foo", "()(%1)", "")` throws the following exception:

```lua
Uncaught Java exception
java.lang.IllegalArgumentException: fromIndex(0) > toIndex(-2)
	at java.base/java.util.Arrays.rangeCheck(Arrays.java:718)
	at java.base/java.util.Arrays.equals(Arrays.java:2702)
	at org.squiddev.cobalt.LuaString.equals(LuaString.java:328)
	at org.squiddev.cobalt.LuaString.equals(LuaString.java:324)
	at org.squiddev.cobalt.lib.StringMatch$MatchState.match_capture(StringMatch.java:676)
	at org.squiddev.cobalt.lib.StringMatch$MatchState.match(StringMatch.java:571)
	at org.squiddev.cobalt.lib.StringMatch$MatchState.start_capture(StringMatch.java:656)
	at org.squiddev.cobalt.lib.StringMatch$MatchState.match(StringMatch.java:538)
	at org.squiddev.cobalt.lib.StringMatch$MatchState.start_capture(StringMatch.java:656)
	at org.squiddev.cobalt.lib.StringMatch$MatchState.match(StringMatch.java:536)
	at org.squiddev.cobalt.lib.StringMatch.gsubRun(StringMatch.java:169)
	at org.squiddev.cobalt.lib.StringLib$GSub.invoke(StringLib.java:152)
```

Not sure how we're constructing an invalid string, but we are!

**Comment by SquidDev** [comment]
Fixed in e7345636306d583c19ea545ee8ab13d108ba12c2.
